# pandas home Exercise :

In [77]:
import numpy as np
import pandas as pd

## Exe 1 :
-------------

In [78]:
# part 1.
person_df = pd.DataFrame(columns=["Name", "Age", "Gender", "Occupation"])

person_df

Empty DataFrame
Columns: [Name, Age, Gender, Occupation]
Index: []

--------

In [79]:
# part 2.
rows = [
    ["Maya Cohen",   29, "Female", "Graphic Designer"],
    ["Daniel Levi",  34, "Male",   "Software Engineer"],
    ["Noa Mizrahi",  26, "Female", "Data Analyst"],
    ["Amir Haddad",  41, "Male",   "Project Manager"],
    ["Lior Ben-Ami", 22, "Male",   "Student"],
]

people = pd.DataFrame(rows, columns=person_df.columns)
person_df = pd.concat([person_df, people], ignore_index=True)

person_df

           Name Age  Gender         Occupation
0    Maya Cohen  29  Female   Graphic Designer
1   Daniel Levi  34    Male  Software Engineer
2   Noa Mizrahi  26  Female       Data Analyst
3   Amir Haddad  41    Male    Project Manager
4  Lior Ben-Ami  22    Male            Student

--------

In [80]:
# part 3.
print(f"the mean of col Age is: {np.mean(person_df["Age"])}")

person_df

the mean of col Age is: 30.4

           Name Age  Gender         Occupation
0    Maya Cohen  29  Female   Graphic Designer
1   Daniel Levi  34    Male  Software Engineer
2   Noa Mizrahi  26  Female       Data Analyst
3   Amir Haddad  41    Male    Project Manager
4  Lior Ben-Ami  22    Male            Student

--------

In [81]:
# part 4.
person_df["Salary"] = [2900, 5000, 3800, 10000, 999]

person_df

           Name Age  Gender         Occupation  Salary
0    Maya Cohen  29  Female   Graphic Designer    2900
1   Daniel Levi  34    Male  Software Engineer    5000
2   Noa Mizrahi  26  Female       Data Analyst    3800
3   Amir Haddad  41    Male    Project Manager   10000
4  Lior Ben-Ami  22    Male            Student     999

--------

In [82]:
# part 5.
person_df.drop("Occupation", axis=1, inplace=True)

person_df

           Name Age  Gender  Salary
0    Maya Cohen  29  Female    2900
1   Daniel Levi  34    Male    5000
2   Noa Mizrahi  26  Female    3800
3   Amir Haddad  41    Male   10000
4  Lior Ben-Ami  22    Male     999

--------

## Exe 2 :
----------

In [83]:
# part 1.
tips_df = pd.read_csv(r"C:\Users\אילעי\Downloads\pyex\JN_learning\pandas_exl\tips (5).csv")

tips_df.head(6)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679

--------

In [84]:
# part 2.
tips_df.set_index("Payment ID", inplace=True)

tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

--------

In [85]:
# part 3.
five_tips = tips_df.loc[["Sun2959","Sun5260","Sat2657","Sat17","Sun4608"]]

five_tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

--------

In [86]:
# part 4.
tips_df["price_per_person"] = (tips_df["total_bill"] + tips_df["tip"]) / tips_df["size"]

tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,9.000,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,4.000,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,8.170,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,13.495,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,7.050,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,11.650,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,14.590,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,12.335,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,9.785,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,10.890,Michelle Hardin,3511451626698139

--------

In [87]:
# part 5.
smoaking_generous_girl = tips_df[(tips_df["sex"] == "Female") & (tips_df["smoker"] == "Yes") & (tips_df["tip"] > 3)]

smoaking_generous_girl

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sat1967,26.86,3.14,Female,Yes,Sat,Dinner,2,15.000000,Victoria Obrien MD,4216245673726
Sat6065,25.28,5.00,Female,Yes,Sat,Dinner,2,15.140000,Julie Holmes,5418689346409571
Fri6963,16.32,4.30,Female,Yes,Fri,Dinner,2,10.310000,Natalie Nguyen,5181236182893396
Sat1015,22.42,3.48,Female,Yes,Sat,Dinner,2,12.950000,Kathleen Hawkins,348009865484721
Sat2614,14.31,4.00,Female,Yes,Sat,Dinner,2,9.155000,Amanda Anderson,375638820334211
Sun4598,9.60,4.00,Female,Yes,Sun,Dinner,2,6.800000,Melanie Gray,4211808859168
Sun4254,20.90,3.50,Female,Yes,Sun,Dinner,3,8.133333,Heidi Atkinson,4422858423131187
Sun430,18.15,3.50,Female,Yes,Sun,Dinner,3,7.216667,Glenda Wiggins,578329325307
Thur967,19.81,4.19,Female,Yes,Thur,Lunch,2,12.000000,Kristy Boyd,4317015327600068
Thur9313,43.11,5.00,Female,Yes,Thur,Lunch,4,12.027500,Brooke Soto,5544902205760175
Thur8084,16.47,3.23,Female,Yes,Thur,Lunch,3,6.566667,Carly Reyes,4787787236486
Sat3374,28.17,6.50,Female,Yes,Sat,Dinner,3,11.556667,Marissa Jackson,4922302538691962
Sat8863,30.14,3.09,Female,Yes,Sat,Dinner,4,8.307500,Shelby House,502097403252
Fri7511,13.42,3.48,Female,Yes,Fri,Lunch,2,8.450000,Leslie Kaufman,379437981958785

--------

## Exe 3 :
--------

In [88]:
np.random.seed(100)

In [89]:
# part 1.
random_mat = np.random.randint(0,100, (4,6))
random_df = pd.DataFrame(random_mat)

random_df

    0   1   2   3   4   5
0   8  24  67  87  79  48
1  10  94  52  98  53  66
2  98  14  34  24  15  60
3  58  16   9  93  86   2

--------

In [90]:
# part 2.
columns = ["1st","2nd","3rd","4th","5th","6th"]
random_df.columns = columns

random_df

   1st  2nd  3rd  4th  5th  6th
0    8   24   67   87   79   48
1   10   94   52   98   53   66
2   98   14   34   24   15   60
3   58   16    9   93   86    2

--------

In [91]:
# part 3.
random_df["row_sum"] = random_df.sum(axis=1)

random_df

   1st  2nd  3rd  4th  5th  6th  row_sum
0    8   24   67   87   79   48      313
1   10   94   52   98   53   66      373
2   98   14   34   24   15   60      245
3   58   16    9   93   86    2      264

--------

In [92]:
# part 4.
col_sum = random_df.sum(axis=0)

col_sum

1st         174
2nd         148
3rd         162
4th         302
5th         233
6th         176
row_sum    1195
dtype: int64

In [93]:
# part 5(rows).
row_max_no_sum = random_df[["1st", "2nd", "3rd", "4th", "5th", "6th"]].max(axis=1)
print(f"this is the max value of each row without the sum:\n{row_max_no_sum}\n")

row_max = random_df.max(axis=1)
print(f"this is the max value of each row with the sum:\n{row_max}\n")

row_min = random_df.min(axis=1)
print(f"this is the min value of each row with the sum:\n{row_min}\n")

this is the max value of each row without the sum:
0    87
1    98
2    98
3    93
dtype: int32

this is the max value of each row with the sum:
0    313
1    373
2    245
3    264
dtype: int64

this is the min value of each row with the sum:
0     8
1    10
2    14
3     2
dtype: int64

In [94]:
# part 5(columns).
col_max = random_df.max(axis=0)
print(f"this is the max value of each column without the sum:\n{col_max}\n")

col_min = random_df.min(axis=0)
print(f"this is the min value of each column without the sum:\n{col_min}\n")

this is the max value of each column without the sum:
1st         98
2nd         94
3rd         67
4th         98
5th         86
6th         66
row_sum    373
dtype: int64

this is the min value of each column without the sum:
1st          8
2nd         14
3rd          9
4th         24
5th         15
6th          2
row_sum    245
dtype: int64

In [95]:
# part 6.
r_df_copy = random_df.copy()

r_df_copy[r_df_copy %2 == 0] = -1

r_df_copy

   1st  2nd  3rd  4th  5th  6th  row_sum
0   -1   -1   67   87   79   -1      313
1   -1   -1   -1   -1   53   -1      373
2   -1   -1   -1   -1   15   -1      245
3   -1   -1    9   93   -1   -1       -1

## Exe 4 :
--------

In [96]:
# part 1.
data_a = {
        'Model': ['Ford Mustang GT', 'Toyota Land Cruiser', 'Ford Explorer', 'Tesla Model X', 'Ford Escape'],
        'In_Stock': [5, 12, 8, 4, 10]
        }
df_a = pd.DataFrame(data_a)

data_b = {
        'Model': ['Tesla Model 3', 'Toyota Corolla', 'Tesla Model X', 'Tesla Model Y', 'Ford F-150'],
        'In_Stock': [15, 3, 2, 20, 1]
        }
df_b = pd.DataFrame(data_b)

data_c = {
        'Model': ['Toyota Corolla', 'Tesla Model 3', 'Toyota RAV4', 'Ford F-150', 'Toyota Land Cruiser'],
        'In_Stock': [25, 18, 14, 9, 6]
        }
df_c = pd.DataFrame(data_c)

print(f"Dealership A:\n{df_a}\n")
print(f"Dealership B:\n{df_b}\n")
print(f"Dealership C:\n{df_c}\n")

Dealership A:
                 Model  In_Stock
0      Ford Mustang GT         5
1  Toyota Land Cruiser        12
2        Ford Explorer         8
3        Tesla Model X         4
4          Ford Escape        10

Dealership B:
            Model  In_Stock
0   Tesla Model 3        15
1  Toyota Corolla         3
2   Tesla Model X         2
3   Tesla Model Y        20
4      Ford F-150         1

Dealership C:
                 Model  In_Stock
0       Toyota Corolla        25
1        Tesla Model 3        18
2          Toyota RAV4        14
3           Ford F-150         9
4  Toyota Land Cruiser         6

In [97]:
# part 2.
def buy_car_1(car_buy_list, df_a, df_b, df_c):
    cars_to_drop_a = df_a[df_a['In_Stock'] <= 0].index
    df_a.drop(cars_to_drop_a, inplace=True)
        
    cars_to_drop_b = df_b[df_b['In_Stock'] <= 0].index
    df_b.drop(cars_to_drop_b, inplace=True)
        
    cars_to_drop_c = df_c[df_c['In_Stock'] <= 0].index
    df_c.drop(cars_to_drop_c, inplace=True)
    
    delership_for_car = {}
    for car in car_buy_list:
        found_delership = []
        
        if car in df_a["Model"].values:
            df_a.loc[df_a["Model"] == car, "In_Stock"] -= 1
            found_delership.append("df_a") 
            if car in df_b["Model"].values:
                found_delership.append("df_b")
            
            if car in df_c["Model"].values:
                found_delership.append("df_c")

        elif car in df_b["Model"].values:
            df_b.loc[df_b["Model"] == car, "In_Stock"] -= 1
            found_delership.append("df_b") 
            if car in df_a["Model"].values:
                found_delership.append("df_a")
            
            if car in df_c["Model"].values:
                found_delership.append("df_c")

        elif car in df_c["Model"].values:
            df_c.loc[df_c["Model"] == car, "In_Stock"] -= 1
            found_delership.append("df_c") 
            if car in df_a["Model"].values:
                found_delership.append("df_a")
            
            if car in df_b["Model"].values:
                found_delership.append("df_b")
        else:
            found_delership.append(None)
        delership_for_car[car] = found_delership
       
    return delership_for_car


car_buy_list = ['Toyota Corolla', 'Tesla Model 3', 'Ford F-150', 'Ford Mustang GT', 'Tesla Model Y', 'Toyota RAV4', "feufgi", 0]
print(buy_car_1(car_buy_list, df_a, df_b, df_c))
print(f"\n {df_a}\n 'n{df_b}\n \n{df_c}\n")

{'Toyota Corolla': ['df_b', 'df_c'], 'Tesla Model 3': ['df_b', 'df_c'], 'Ford F-150': ['df_b', 'df_c'], 'Ford Mustang GT': ['df_a'], 'Tesla Model Y': ['df_b'], 'Toyota RAV4': ['df_c'], 'feufgi': [None], 0: [None]}

                  Model  In_Stock
0      Ford Mustang GT         4
1  Toyota Land Cruiser        12
2        Ford Explorer         8
3        Tesla Model X         4
4          Ford Escape        10
 'n            Model  In_Stock
0   Tesla Model 3        14
1  Toyota Corolla         2
2   Tesla Model X         2
3   Tesla Model Y        19
4      Ford F-150         0

                 Model  In_Stock
0       Toyota Corolla        25
1        Tesla Model 3        18
2          Toyota RAV4        13
3           Ford F-150         9
4  Toyota Land Cruiser         6